### ISSUE TITLE
OT conection issue EcoCondensSilver

### ISSUE THREAD

**Issue by esys4u** [jacek27/wemos_open_therm#2]
Seems it's now working for me, I'm getting 

[C][logger:416]: Logger:
[C][logger:417]:   Level: DEBUG
[C][logger:418]:   Log Baud Rate: 115200
[C][logger:420]:   Hardware UART: UART0
[C][opentherm:262]: OpenTherm:
[C][opentherm:263]:   In: GPIO5
[C][opentherm:264]:   Out: GPIO4
[C][opentherm:265]:   Sensors: rel_mod_level_sensor ch_pressure_sensor dhw_flow_rate_sensor t_boiler_sensor t_dhw_sensor t_outside_sensor t_ret_sensor t_storage_sensor t_collector_sensor t_flow_ch2_sensor t_dhw2_sensor t_exhaust_sensor burner_starts_sensor ch_pump_starts_sensor dhw_pump_valve_starts_sensor dhw_burner_starts_sensor burner_operation_hours_sensor ch_pump_operation_hours_sensor dhw_pump_valve_operation_hours_sensor dhw_burner_operation_hours_sensor t_dhw_set_ub_sensor t_dh
....

and many 
[W][opentherm:190]: Received invalid OpenTherm response: 0, status=3 for all sensors

my setup:
`esphome:
  name: esphome-web-d1a832
  friendly_name: thermostat

esp8266:
  board: d1_mini

logger:

api:
  encryption:
    key: "***"

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "***"
    password: "***"

captive_portal:

external_components:
  source: github://arthurrump/esphome-opentherm@main
 
opentherm:
  in_pin: 5
  out_pin: 4
  ch_enable: true
  dhw_enable: true
 
sensor:
  - platform: opentherm
    rel_mod_level:
      name: "Boiler Relative modulation level"
    ch_pressure:
      name: "Boiler Water pressure in CH circuit"
    dhw_flow_rate:
      name: "Boiler Water flow rate in DHW circuit"
    t_boiler:
      name: "Boiler water temperature"
    t_dhw:
      name: "Boiler DHW temperature"
    t_outside:
      name: "Boiler Outside temperature"
    t_ret:
      name: "Boiler Return water temperature"
    t_storage:
      name: "Boiler Solar storage temperature"
    t_collector:
      name: "Boiler Solar collector temperature"
    t_flow_ch2:
      name: "Boiler Flow water temperature CH2 circuit"
    t_dhw2:
      name: "Boiler Domestic hot water temperature 2"
    t_exhaust:
      name: "Boiler Exhaust temperature"
    burner_starts:
      name: "Boiler Number of starts burner"
    ch_pump_starts:
      name: "Boiler Number of starts CH pump"
    dhw_pump_valve_starts:
      name: "Boiler Number of starts DHW pump/valve"
    dhw_burner_starts:
      name: "Boiler Number of starts burner during DHW mode"
    burner_operation_hours:
      name: "Boiler Number of hours that burner is in operation (i.e. flame on)"
    ch_pump_operation_hours:
      name: "Boiler Number of hours that CH pump has been running"
    dhw_pump_valve_operation_hours:
      name: "Boiler Number of hours that DHW pump has been running or DHW valve has been opened"
    dhw_burner_operation_hours:
      name: "Boiler Number of hours that burner is in operation during DHW mode"
    t_dhw_set_ub:
      name: "Boiler Upper bound for adjustement of DHW setpoint"
    t_dhw_set_lb:
      name: "Boiler Lower bound for adjustement of DHW setpoint"
    max_t_set_ub:
      name: "Boiler Upper bound for adjustement of max CH setpoint"
    max_t_set_lb:
      name: "Boiler Lower bound for adjustement of max CH setpoint"
    t_dhw_set:
      name: "Boiler Domestic hot water temperature setpoint"
    max_t_set:
      name: "Boiler Maximum allowable CH water setpoint"`

**Comment by ReactiveThings** [comment]
@esys4u I have the same issue. How have you fixed it?
